# Generated by Django 5.2.13 on 2026-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['user'], name='oauth_accou_user_id_9d8b45_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['provider'], name='oauth_accou_provide_bf96d7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
