# Generated by Django 5.2.13 on 2026-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['category', 'availability_status'], name='rooms_categor_5b11c3_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='rooms_price_p_db2697_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['rating'], name='rooms_rating_556158_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_featured', 'created_at'], name='rooms_is_feat_25969e_idx'),
        ),
    ]
