# Generated by Django 5.2.13 on 2026-05-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_rooms_categor_5b11c3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(help_text='e.g. cancellation, check_in, pets', max_length=50),
        ),
    ]
