# Generated by Django 5.2.13 on 2026-04-29 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0002_room_rooms_categor_5b11c3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'created_at'], name='bookings_user_id_ce04f0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_status_8f492c_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_ref'], name='bookings_booking_ea21fb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_check_i_759ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingroom',
            index=models.Index(fields=['booking'], name='booking_roo_booking_f0422b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingroom',
            index=models.Index(fields=['room'], name='booking_roo_room_id_c11343_idx'),
        ),
    ]
