# Generated by Django 5.2.13 on 2026-05-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_time',
            field=models.TimeField(default='11:00:00', help_text='Checkout time, default 11:00 AM'),
        ),
    ]
