# Generated by Django 6.0.4 on 2026-05-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_checkout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_time',
            field=models.TimeField(default='14:00:00', help_text='Check-in time, default 2:00 PM'),
        ),
    ]
