# Generated by Django 6.0.4 on 2026-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_arrival_time',
            field=models.TimeField(blank=True, help_text='Estimated time of arrival', null=True),
        ),
    ]
