# Generated by Django 5.2.13 on 2026-05-13 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_estimated_arrival_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Additional details about cancellation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('change_of_plans', 'Change of Plans'), ('found_better_deal', 'Found Better Deal'), ('booking_error', 'Booking Error'), ('travel_restrictions', 'Travel Restrictions'), ('emergency', 'Emergency'), ('weather_issues', 'Weather Issues'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['cancelled_at'], name='bookings_cancell_94ed87_idx'),
        ),
    ]
